apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: asia-southeast1-docker.pkg.dev/gke-projects-494002/next-js/nextjs-standalone:0.1.0
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
