apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: <YOUR_REGISTRY>/<YOUR_PROJECT>/<YOUR_IMAGE>:<VERSION>
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
